encoder_params:
  input_dim: 256
  hidden_dims: null
  latent_dim: 64

decoder_params:
  latent_dim: 64
  hidden_dims: null
  output_dim: 256

loss_params:
  kl_coeff: 0.01

stage1_params:
  model: 'vanilla_vae'

exp_params:
  model_name: 'two_stage_vae'
  dataset: celeba
  data_path: "kaggle"
  img_size: 64
  crop_size: 128
  batch_size: 256 # Better to have a square number
  LR: 0.001
  template: "2 stage vae"

trainer_params:
  gpus: 1
  max_epochs: 30